<footer>
  <div class="footer_nav">
    <ul class="footer_links">
      <li><a href="index.php">Home</a></li>
      <li><a href="about.php">About</a></li>
      <li><a href="jobs.php">Jobs</a></li>
      <li><a href="apply.php">Apply</a></li>
    </ul>
  </div>

  <div id="footer_row">
    <a class="footer_link" href="https://github.com/Ollie-S23/OliverPortfolio_Website.git" target="_blank">
      Github Repo Link
    </a>
  </div>

  <p id="copyright">&copy; Copyright <?php echo date("Y"); ?> | Oliver Scott | All Rights Reserved</p>
</footer>
